export enum Status {
	// DRAFTED = "DRAFTED",
	// PREPARED = "PREPARED",
	// ASSIGNED = "ASSIGNED",
	// PENDING = "PENDING",
	// SIGNED = "SIGNED",	
	// ARCHIVED = "ARCHIVED"
	NEW = 'NEW',
	DRAFTED = 'DRAFTED',
	PARTIES = 'PARTIES',
	CLAUSES = 'CLAUSES',
	FINALIZED = 'FINALIZED',
	SENT = 'SENT',
	SIGNED = 'SIGNED'
}